-- Quartz JDBC JobStore 表结构，表名和字段名受 Quartz 框架约束，不作为 TradN 业务表直接修改。
-- 任务定义与触发器元数据。
CREATE TABLE QRTZ_JOB_DETAILS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  JOB_NAME VARCHAR(200) NOT NULL COMMENT '任务名称',
  JOB_GROUP VARCHAR(200) NOT NULL COMMENT '任务分组',
  DESCRIPTION VARCHAR(250) NULL COMMENT '任务说明',
  JOB_CLASS_NAME VARCHAR(250) NOT NULL COMMENT '任务实现类全限定名',
  IS_DURABLE VARCHAR(1) NOT NULL COMMENT '是否持久任务',
  IS_NONCONCURRENT VARCHAR(1) NOT NULL COMMENT '是否禁止并发执行',
  IS_UPDATE_DATA VARCHAR(1) NOT NULL COMMENT '执行后是否更新任务数据',
  REQUESTS_RECOVERY VARCHAR(1) NOT NULL COMMENT '是否请求故障恢复',
  JOB_DATA BLOB NULL COMMENT '序列化任务数据',
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
) ENGINE=InnoDB COMMENT='Quartz任务定义';

CREATE TABLE QRTZ_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器分组',
  JOB_NAME VARCHAR(200) NOT NULL COMMENT '关联任务名称',
  JOB_GROUP VARCHAR(200) NOT NULL COMMENT '关联任务分组',
  DESCRIPTION VARCHAR(250) NULL COMMENT '触发器说明',
  NEXT_FIRE_TIME BIGINT NULL COMMENT '下次触发时间戳（毫秒）',
  PREV_FIRE_TIME BIGINT NULL COMMENT '上次触发时间戳（毫秒）',
  PRIORITY INTEGER NULL COMMENT '触发优先级',
  TRIGGER_STATE VARCHAR(16) NOT NULL COMMENT '触发器状态',
  TRIGGER_TYPE VARCHAR(8) NOT NULL COMMENT '触发器类型',
  START_TIME BIGINT NOT NULL COMMENT '生效开始时间戳（毫秒）',
  END_TIME BIGINT NULL COMMENT '失效结束时间戳（毫秒）',
  CALENDAR_NAME VARCHAR(200) NULL COMMENT '关联Quartz日历名称',
  MISFIRE_INSTR SMALLINT NULL COMMENT '错过触发处理指令',
  JOB_DATA BLOB NULL COMMENT '序列化触发器数据',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  KEY IDX_QRTZ_T_J (SCHED_NAME,JOB_NAME,JOB_GROUP),
  KEY IDX_QRTZ_T_STATE (SCHED_NAME,TRIGGER_STATE),
  KEY IDX_QRTZ_T_NEXT_FIRE_TIME (SCHED_NAME,NEXT_FIRE_TIME)
) ENGINE=InnoDB COMMENT='Quartz触发器主表';

-- 不同触发器类型的扩展参数表，均通过复合主键关联 QRTZ_TRIGGERS。
CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器分组',
  REPEAT_COUNT BIGINT NOT NULL COMMENT '重复执行次数',
  REPEAT_INTERVAL BIGINT NOT NULL COMMENT '重复间隔毫秒数',
  TIMES_TRIGGERED BIGINT NOT NULL COMMENT '已经触发次数',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB COMMENT='Quartz简单触发器参数';

CREATE TABLE QRTZ_CRON_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器分组',
  CRON_EXPRESSION VARCHAR(200) NOT NULL COMMENT 'Quartz Cron表达式',
  TIME_ZONE_ID VARCHAR(80) COMMENT 'Cron计算时区ID',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB COMMENT='Quartz Cron触发器参数';

CREATE TABLE QRTZ_SIMPROP_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器分组',
  STR_PROP_1 VARCHAR(512) NULL COMMENT '字符串扩展属性1',
  STR_PROP_2 VARCHAR(512) NULL COMMENT '字符串扩展属性2',
  STR_PROP_3 VARCHAR(512) NULL COMMENT '字符串扩展属性3',
  INT_PROP_1 INT NULL COMMENT '整数扩展属性1',
  INT_PROP_2 INT NULL COMMENT '整数扩展属性2',
  LONG_PROP_1 BIGINT NULL COMMENT '长整数扩展属性1',
  LONG_PROP_2 BIGINT NULL COMMENT '长整数扩展属性2',
  DEC_PROP_1 NUMERIC(13,4) NULL COMMENT '小数扩展属性1',
  DEC_PROP_2 NUMERIC(13,4) NULL COMMENT '小数扩展属性2',
  BOOL_PROP_1 VARCHAR(1) NULL COMMENT '布尔扩展属性1',
  BOOL_PROP_2 VARCHAR(1) NULL COMMENT '布尔扩展属性2',
  TIME_ZONE_ID VARCHAR(80) NULL COMMENT '触发器时区ID',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB COMMENT='Quartz属性型触发器参数';

CREATE TABLE QRTZ_BLOB_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器分组',
  BLOB_DATA BLOB NULL COMMENT '序列化触发器扩展数据',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB COMMENT='Quartz二进制触发器参数';

-- Quartz 日历、暂停组、已触发实例、集群状态与分布式锁。
CREATE TABLE QRTZ_CALENDARS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  CALENDAR_NAME VARCHAR(200) NOT NULL COMMENT '日历名称',
  CALENDAR BLOB NOT NULL COMMENT '序列化Quartz日历对象',
  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
) ENGINE=InnoDB COMMENT='Quartz日历';

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '被暂停的触发器分组',
  PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
) ENGINE=InnoDB COMMENT='Quartz暂停触发器分组';

CREATE TABLE QRTZ_FIRED_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  ENTRY_ID VARCHAR(95) NOT NULL COMMENT '已触发实例唯一ID',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器分组',
  INSTANCE_NAME VARCHAR(200) NOT NULL COMMENT '执行调度器实例名称',
  FIRED_TIME BIGINT NOT NULL COMMENT '实际触发时间戳（毫秒）',
  SCHED_TIME BIGINT NOT NULL COMMENT '计划触发时间戳（毫秒）',
  PRIORITY INTEGER NOT NULL COMMENT '触发优先级',
  STATE VARCHAR(16) NOT NULL COMMENT '执行实例状态',
  JOB_NAME VARCHAR(200) NULL COMMENT '关联任务名称',
  JOB_GROUP VARCHAR(200) NULL COMMENT '关联任务分组',
  IS_NONCONCURRENT VARCHAR(1) NULL COMMENT '是否禁止并发执行',
  REQUESTS_RECOVERY VARCHAR(1) NULL COMMENT '是否请求故障恢复',
  PRIMARY KEY (SCHED_NAME,ENTRY_ID),
  KEY IDX_QRTZ_FT_TRIG_INST_NAME (SCHED_NAME,INSTANCE_NAME),
  KEY IDX_QRTZ_FT_J_G (SCHED_NAME,JOB_NAME,JOB_GROUP)
) ENGINE=InnoDB COMMENT='Quartz已触发任务实例';

CREATE TABLE QRTZ_SCHEDULER_STATE (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  INSTANCE_NAME VARCHAR(200) NOT NULL COMMENT '调度器实例名称',
  LAST_CHECKIN_TIME BIGINT NOT NULL COMMENT '最近集群检入时间戳（毫秒）',
  CHECKIN_INTERVAL BIGINT NOT NULL COMMENT '集群检入间隔毫秒数',
  PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
) ENGINE=InnoDB COMMENT='Quartz集群调度器状态';

CREATE TABLE QRTZ_LOCKS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Quartz调度器名称',
  LOCK_NAME VARCHAR(40) NOT NULL COMMENT 'Quartz分布式锁名称',
  PRIMARY KEY (SCHED_NAME,LOCK_NAME)
) ENGINE=InnoDB COMMENT='Quartz分布式锁';

-- Quartz 官方表之间的完整性约束；删除任务时由调度器按依赖顺序维护。
ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT FK_QRTZ_TRIGGER_JOB FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP);
ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPLE_TRIGGER FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT FK_QRTZ_CRON_TRIGGER FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPROP_TRIGGER FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT FK_QRTZ_BLOB_TRIGGER FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
